export const roots = {
  HOME: 'home',
  EXPLORE: 'explore',
  CREATE: 'create',
  PORTFOLIO: 'portfolio',
  ACCOUNT: 'account',
}

const paths = {
  HOME: {
    ROOT: roots.HOME,
    USER_PROFILE: `${roots.HOME}/user-profile`,
    SUBFORUM_DETAIL: `${roots.HOME}/subforum-detail`,
    POST_DETAIL: `${roots.HOME}/post-detail`,
    TAG_DETAIL: `${roots.HOME}/tag-detail`,
    ASSET_DETAIL: `${roots.HOME}/asset-detail`,
  },
  EXPLORE: {
    ROOT: roots.EXPLORE,
    SEARCH: `${roots.EXPLORE}/search`,
    SEARCH_RESULTS: {
      ASSET_DETAIL: `${roots.EXPLORE}/search/asset-detail`,
      POST_DETAIL: `${roots.EXPLORE}/search/post-detail`,
      USER_PROFILE: `${roots.EXPLORE}/search/user-profile`,
      SUBFORUM_DETAIL: `${roots.EXPLORE}/search/subforum-detail`,
      TAG_DETAIL: `${roots.EXPLORE}/search/tag-detail`,
    },
    USER_PROFILE: `${roots.EXPLORE}/user-profile`,
    SUBFORUM_DETAIL: `${roots.EXPLORE}/subforum-detail`,
    POST_DETAIL: `${roots.EXPLORE}/post-detail`,
    ASSET_DETAIL: `${roots.EXPLORE}/asset-detail`,
    TAG_DETAIL: `${roots.EXPLORE}/tag-detail`,
  },
  CREATE: {
    ROOT: roots.CREATE,
    ADD_POST: `${roots.CREATE}/add-post`,
    ADD_SUBFORUM: `${roots.CREATE}/add-subforum`,
    ADD_SUBFORUM_POST: `${roots.CREATE}/add-subforum-post`,
  },
  PORTFOLIO: {
    ROOT: roots.PORTFOLIO,
    ADD_ASSET: `${roots.PORTFOLIO}/add-asset`,
    SUBFORUM_DETAIL: `${roots.PORTFOLIO}/subforum-detail`,
    ASSET_DETAIL: `${roots.PORTFOLIO}/asset-detail`,
    TAG_DETAIL: `${roots.PORTFOLIO}/tag-detail`,
    POST_DETAIL: `${roots.PORTFOLIO}/post-detail`,
    USER_PROFILE: `${roots.PORTFOLIO}/user-profile`,
  },
  ACCOUNT: {
    ROOT: roots.ACCOUNT,
    PROFILE: `${roots.ACCOUNT}/profile`,
    PORTFOLIO: `${roots.ACCOUNT}/portfolio`,
    FOLLOWED_TOPICS: `${roots.ACCOUNT}/followed-topics`,
    FOLLOWED_USERS: `${roots.ACCOUNT}/followed-users`,
    MY_POSTS: `${roots.ACCOUNT}/my-posts`,
    FOLLOWERS: `${roots.ACCOUNT}/followers`,
    FOLLOWINGS: `${roots.ACCOUNT}/followings`,
    USER_PROFILE: `${roots.ACCOUNT}/user-profile`,
    POST_DETAIL: `${roots.ACCOUNT}/post-detail`,
    ASSET_DETAIL: `${roots.ACCOUNT}/asset-detail`,
    TAG_DETAIL: `${roots.ACCOUNT}/tag-detail`,
    SUBFORUM_DETAIL: `${roots.ACCOUNT}/subforum-detail`,
  },
}
export default paths
