version: '3.8'
<<<<<<< HEAD
services:
  mysql_server:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: animaltroove
    ports:
      - "3306:3306"
    volumes:
      - ./src/DB.sql:/docker-entrypoint-initdb.d/init.sql

  java_app:
    image: openjdk:21-jdk
    depends_on:
      - mysql_server
    ports:
      - "8080:8080"
    command: java -jar animaltroove-0.0.1-SNAPSHOT.jar --spring.datasource.url=jdbc:mysql://mysql_server:3306/animaltroove --spring.datasource.username=root --spring.datasource.password=root
    build:
      context: .
      dockerfile: Dockerfile
      target: java_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_server:3306/animaltroove?useSSL=false&serverTimezone=UTC
=======

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: animaltroove
      MYSQL_USER: animaltroove
      MYSQL_PASSWORD: admin123
    ports:
      - "3306"
    volumes:
      - ./DBSQL:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "animaltroove", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 3

  animaltroove:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080"

>>>>>>> d6b569fc10d937493756258c04b89ddf3877eb55
